// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMbXCYJLsUf_JwE8Ok3MSlz5cP6DwsJYY',
    appId: '1:562433583187:android:a85ba63bb345c6c4ad7ea6',
    messagingSenderId: '562433583187',
    projectId: 'hangr-fc824',
    databaseURL: 'https://hangr-fc824-default-rtdb.firebaseio.com',
    storageBucket: 'hangr-fc824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8czfwzxZ450bMIqJBvUcND7W4doXzY-4',
    appId: '1:562433583187:ios:4054198b5768fcd8ad7ea6',
    messagingSenderId: '562433583187',
    projectId: 'hangr-fc824',
    databaseURL: 'https://hangr-fc824-default-rtdb.firebaseio.com',
    storageBucket: 'hangr-fc824.appspot.com',
    iosClientId: '562433583187-i5sb89g0uk199t3b0kg8u7f9u5bfbqb6.apps.googleusercontent.com',
    iosBundleId: 'com.canada.hangr',
  );
}
