/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontFam2 = 'CustomIcons2';

  static const IconData accessory = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bottom = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData footwear = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData headwear = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData top = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData athletic = IconData(0xe800, fontFamily: _kFontFam2);
  static const IconData business = IconData(0xe801, fontFamily: _kFontFam2);
  static const IconData formal = IconData(0xe802, fontFamily: _kFontFam2);
}
